config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  scope module: :public do
    root :to =>"homes#top"
    get "home/about"=>"homes#about"
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :customers, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
  	  get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
    end
    get '/search_result', to: 'searches#search_result'
    resources :chats, only: [:show, :create]
  end

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  namespace :admin do
    root :to =>"homes#top"
    resources :customers, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  #文字制限140文字以内
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_one_attached :profile_image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
    # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #DM機能
  has_many :customer_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  #初期画像
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  #フォローしたときの処理
  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end
  #フォローを外すときの処理
  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end
  #フォローしているか判定
  def following?(customer)
    followings.include?(customer)
  end
  #guestメソッドの定義
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end
  #会員の検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("name LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end
end

app/models/customer_room.rb
class CustomerRoom < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  #投稿で空欄が無いようにするバリデーション
  validates :team_name, presence:true
  validates :personnom, presence:true
  validates :base, presence:true

  #引数で渡されたユーザidがFavoritesテーブル内に存在するかどうか
  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
  #投稿の検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("team_name LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("team_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("team_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("team_name LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :customer_rooms
end

app/controllers/admin/chats_controller.rb
class Admin::ChatsController < ApplicationController
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    #会員全員の情報
    @customers = Customer.all
  end

  def show
    #選択した会員の情報
    @customer = Customer.find(params[:id])
    #選択した会員が投稿したもの一覧
    @posts = @customer.posts
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_admin!, if: :admin_url

  def after_sign_in_path_for(resource)
    customers_path
  end

  def after_sign_up_path_for(resource)
    customers_path
  end

  protected

  def admin_url
    request.fullpath.include?("/admin")
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:email])
  end

end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Devise::SessionsController
  #ゲストログイン関係
  def guest_sign_in
    customer = Customer.guest
    sign_in customer
    redirect_to customer_path(customer), notice: 'guestuserでログインしました。'
  end
end

app/helpers/admin/chats_helper.rb
module Admin::ChatsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_comments_helper.rb
module Admin::PostsCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/relationships_helper.rb
module Admin::RelationshipsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/index.html.erb
<div class='container px-5 px-sm-0'>
  <h2>管理者</h2>
  <div class='row'>
    <div class="col-md-10">
      <table class='table'>
        <thead>
          <tr>
            <th>画像</th>
            <th>名前</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <%#会員が設定した画像%>
              <td><%= image_tag customer.get_profile_image, size: '50x50' %></td>
              <%#会員の名前%>
              <td><%= customer.name %></td>
              <td>フォロー数: <%= customer.followings.count %></td>
              <td>フォロワー数: <%= customer.followers.count %></td>
              <td><%= link_to 'Show', admin_customer_path(customer.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>会員情報</h2>
      <table class='table'>
        <tr><%= image_tag @customer.get_profile_image, size:'100x100' %></tr>
        <tr>
          <th>
            name
          </th>
          <th>
            <%= @customer.name %>
          </th>
          <th></th>
        </tr>
      </table>
    </div>
    <div class='col-md-8 offset-md-1'>
      <table class="table">
        <thead>
          <tr>
            <th>チーム名</th>
            <th>人数</th>
            <th>拠点</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <%#投稿のチーム名%>
              <td><%= post.team_name %></td>
              <%#投稿の人数%>
              <td><%= post.personnom %></td>
              <%#投稿の拠点%>
              <td><%= post.base %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>